Exhys/Exhys.WebContestHost/Areas/Shared/ViewModels/UserAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Web;
using Exhys.WebContestHost.DataModels;
using System.Web.Mvc;

namespace Exhys.WebContestHost.Areas.Shared.ViewModels
{
    public class UserAccountViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string FullName { get; set; }
        public bool IsAdmin { get; set; }
        public bool RequestDelete { get; set; }
        public int UserId { get;  set; }
        public int? GroupId { get; set; }
        public string GroupName { get; set; }

        public UserAccountViewModel () : this(null) { }
        public UserAccountViewModel (UserAccount model)
        {
            if (model != null)
            {
                Username = model.Username;
                FullName = model.FullName;
                Password = model.Password;
                if (model.UserGroup != null)
                {
                    this.IsAdmin = model.UserGroup.IsAdministrator;
                    this.GroupId = model.UserGroup.Id;
                    this.GroupName = model.UserGroup.Name;
                }
                this.UserId = model.Id;
            }
            else
            {
                this.IsAdmin = false;
            }
            this.RequestDelete = false;
        }

        private void ValidateUsername(ViewDataDictionary viewData)
        {
            if (Username == null || Username.Length < DatabaseLimits.Username_MinLength)
            {
                viewData.ModelState.AddModelError(FormErrors.UsernameTooShort);
            }
            else if (Username.Length > DatabaseLimits.Username_MaxLength)
            {
                viewData.ModelState.AddModelError(FormErrors.UsernameTooLong);
            }
        }

        private void ValidateNameAndGroup(ViewDataDictionary viewData)
        {
            if ((FullName != null && FullName.Length > DatabaseLimits.HumanName_MaxLength))
            {
                viewData.ModelState.AddModelError(FormErrors.HumanNameTooLong);
            }

            if (GroupId == null)
            {
                viewData.ModelState.AddModelError(FormErrors.NoGroupSelected);
            }
        }

        public bool ValidateForRegistration (ViewDataDictionary viewData)
        {
            ValidateUsername(viewData);

            if (Password == null || Password.Length < DatabaseLimits.Password_MinLength)
            {
                viewData.ModelState.AddModelError(FormErrors.PasswordTooShort);
            }
            else if (Password.Length > DatabaseLimits.Password_MaxLength)
            {
                viewData.ModelState.AddModelError(FormErrors.PasswordTooLong);
            }

            if (Password != ConfirmPassword)
            {
                viewData.ModelState.AddModelError(FormErrors.PasswordMismatch);
            }

            ValidateNameAndGroup(viewData);

            return viewData.ModelState.IsValid;
        }

        public bool ValidateForEdit (ViewDataDictionary viewData)
        {
            if (!string.IsNullOrEmpty(Password))
            {
                if (Password.Length < DatabaseLimits.Password_MinLength)
                {
                    viewData.ModelState.AddModelError(FormErrors.PasswordTooShort);
                }
                else if (Password.Length > DatabaseLimits.Password_MaxLength)
                {
                    viewData.ModelState.AddModelError(FormErrors.PasswordTooLong);
                }
                if (Password != ConfirmPassword)
                {
                    viewData.ModelState.AddModelError(FormErrors.PasswordMismatch);
                }
            }

            ValidateNameAndGroup(viewData);

            return viewData.ModelState.IsValid;
        }

        public bool ValidateForSignIn(ViewDataDictionary viewData)
        {
            ValidateUsername(viewData);

            if (Password == null || Password.Length < DatabaseLimits.Password_MinLength)
            {
                viewData.ModelState.AddModelError(FormErrors.PasswordTooShort);
            }
            else if (Password.Length > DatabaseLimits.Password_MaxLength)
            {
                viewData.ModelState.AddModelError(FormErrors.PasswordTooLong);
            }

            return viewData.ModelState.IsValid;
        }
    }
}

Exhys/Exhys.WebContestHost/Areas/Administration/Controllers/UserAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Exhys.WebContestHost.Areas.Shared;
using Exhys.WebContestHost.Areas.Shared.ViewModels;
using Exhys.WebContestHost.DataModels;
using CodeBits;
using Exhys.WebContestHost.Areas.Shared.Mvc;
using Exhys.WebContestHost.Areas.Shared.Extensions;
using System.Data.Entity;

namespace Exhys.WebContestHost.Areas.Administration.Controllers

{
    [AuthorizeExhysAdmin]
    public class UserAccountsController : ExhysController
    {

		[HttpGet]
        public ActionResult List()
        {
            AddSignedInUserInformation();
            AddUserGroupOptions();

			using (var db=new ExhysContestEntities())
            {
                var vm = new List<UserAccountViewModel>();
                db.UserAccounts
                    .OrderBy(a=>a.Username)
                    .Include(u=>u.UserGroup)
                    .ToList()
                    .ForEach((acc) =>
                    {
                        vm.Add(new UserAccountViewModel(acc));
                    });
                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult List (List<UserAccountViewModel> vm)
        {
            using (var db = new ExhysContestEntities())
            {
                foreach (var v in vm)
                {
                    var user = db.UserAccounts
                        .Where(u => u.Id == v.UserId)
                        .Include(u=>u.UserGroup)
                        .FirstOrDefault();
                    if (v.RequestDelete == false)
                    {
                        user.FullName = v.FullName;
                        user.Password = v.Password;
                        UserGroup gr = db.UserGroups.Where(g => g.Id == v.GroupId).FirstOrDefault();
                        user.UserGroup = gr;
                    }
                    else
                    {
                        db.UserAccounts.Remove(user);
                    }
                    db.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult AddMany()
        {
            AddSignedInUserInformation();
            AddUserGroupOptions();

            return View();
        }

        [HttpPost]
        public ActionResult AddMany (string prefix, int? count, string fullNames, int groupId)
        { 
            if (prefix == null || count == null) return RedirectToAction("AddUsers");
            else
            {
                List<string> peopleNames = fullNames.Split('\n').ToList().Resize(count.Value, "");

                using (var db = new ExhysContestEntities())
                {
                    var gr = db.UserGroups.Where(g => g.Id == groupId).FirstOrDefault();

                    int addedCount = 0;
                    for (int currentNumber = 0; addedCount != count; currentNumber++)
                    {
                        string currentUsername = string.Format("{0}{1:000}", prefix, currentNumber);

                        var existing = db.UserAccounts.Where(u => u.Username == currentUsername).FirstOrDefault();
                        if (existing != null)
                        {
                            //currentUsername is taken
                            continue;
                        }

                        var user = new UserAccount()
                        {
                            Username = currentUsername,
                            Password = PasswordGenerator.Generate(6, PasswordCharacters.AlphaNumeric).ToLower(),
                            FullName = peopleNames[addedCount],
                            UserGroup = gr
                        };
                        db.UserAccounts.Add(user);
                        addedCount++;
                    }
                    db.SaveChanges();
                }
                return RedirectToAction("List");
            }
        }
    }
}

Exhys/Exhys.WebContestHost/Areas/Administration/Views/UserAccounts/AddMany.cshtml
@{
	ViewData.SetPageTitle("Add Users");
}

<div>
	<br /><br />
	<div class="col-lg-6">
		@using(Html.BeginForm("AddMany", "UserAccounts", FormMethod.Post, new { @class = "form-horizontal well" }))
		{
			<fieldset>
				<legend>Register Users</legend>
				<div class="form-group">
					<label for="inputPrefix" class="col-lg-2 control-label">Prefix</label>
					<div class="col-lg-10">
						<input type="text" class="form-control" id="inputPrefix" placeholder="Prefix" name="prefix" value="A" />
					</div>
				</div>
				<div class="form-group">
					<label for="input-count" class="col-lg-2 control-label">Count</label>
					<div class="col-lg-10">
						<input class="form-control" min="1" id="input-count" type="number" placeholder="Count" name="count" value="10" onchange="document.getElementById('txt1').rows = document.getElementById('input-count').rows = document.getElementById('input-count').value;" />
					</div>
				</div>
				<div class="form-group">
					<label for="select" class="col-lg-2 control-label">Group</label>
					<div class="col-lg-10">
						@Html.FixedDropDownListFor("groupId", ViewData.GetUserGroupOptions(), new { @class = "form-control padding-0" })
					</div>
				</div>
				<div class="form-group">
					<label for="txt1" class="col-lg-2 control-label">Names</label>
					<div class="col-lg-10">
						<textarea class="form-control" name="fullNames" rows="10" id="txt1" style="resize:none" placeholder="Competitor First Names (separated by new lines)"></textarea>
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-10 col-lg-offset-2">
						<button type="reset" class="btn btn-default">Reset</button>
						<button type="submit" class="btn btn-primary">Add Users</button>
					</div>
				</div>
			</fieldset>
		}
	</div>
</div>

Exhys/Exhys.WebContestHost/Areas/Administration/Views/UserAccounts/List.cshtml
@model List<UserAccountViewModel>
@{
	ViewData.SetPageTitle("List Users");
}
<div>
	<div>
		<br />
		@using(Html.BeginForm(FormMethod.Post))
		{
			<button type="submit">Save Changes</button>
			<br /><br />
			<table class="table table-hover table-bordered table-striped">
				<thead class="th-center">
					<tr>
						<th>No.</th>
						<th>User ID</th>
						<th>Username</th>
						<th>Password</th>
						<th>Group</th>
						<th>Name</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					@{
						for(int i = 0; i < Model.Count; i++)
						{
							<tr class="valign-middle">
								<td class="text-center">
									@(i + 1)
								</td>
								<td class="text-center">
									@Html.HiddenFor(m => m[i].UserId)
									@Model[i].UserId
								</td>
								<td>
									@Html.HiddenFor(m => m[i].Username, new { readOnly = "" })
									@Model[i].Username
								</td>
								<td>
									@Html.TextBoxFor(m => m[i].Password, new { Class = "form-control height-25px" })
								</td>
								<td>
									@Html.FixedDropDownListFor(m => m[i].GroupId, ViewData.GetUserGroupOptions(), new { Class= "form-control height-25px padding-0" })
								</td>
								<td>
									@Html.TextBoxFor(m => m[i].FullName, new { Class = "form-control height-25px" })
								</td>
								<td class="text-center">
									@Html.CheckBoxFor(m => m[i].RequestDelete)
								</td>
							</tr>
						}
					}
				</tbody>
			</table>
			<button type="submit">Save Changes</button>
		}
	</div>
</div>