Exhys/Exhys.WebContestHost/Areas/Shared/ViewModels/UserGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exhys.WebContestHost.DataModels;

namespace Exhys.WebContestHost.Areas.Shared.ViewModels
{
    public class UserGroupViewModel
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsOpen { get; set; }
        public bool RequestDelete { get; set; }


        public UserGroupViewModel () : this(null) { }
        public UserGroupViewModel (UserGroup model)
        {
            if (model != null)
            {
                Id = model.Id;
                Name = model.Name;
                Description = model.Description;
                IsAdmin = model.IsAdministrator;
                IsOpen = model.IsOpen;
                RequestDelete = false;
            }
        }

        public bool Validate(ViewDataDictionary viewData)
        {
            if(Name==null || Name.Length < DatabaseLimits.UserGroupName_MinLength)
            {
                viewData.ModelState.AddModelError(FormErrors.UserGroupNameTooShort);
            }
            else if(Name.Length > DatabaseLimits.UserGroupName_MaxLength)
            {
                viewData.ModelState.AddModelError(FormErrors.UserGroupNameTooLong);
            }

            return viewData.ModelState.IsValid;
        }

        
    }
}

Exhys/Exhys.WebContestHost/Areas/Administration/Controllers/UserGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exhys.WebContestHost.Areas.Shared.Mvc;
using Exhys.WebContestHost.Areas.Shared.ViewModels;
using Exhys.WebContestHost.DataModels;
using System.Data.Entity.Validation;
using System.Data.Entity;

namespace Exhys.WebContestHost.Areas.Administration.Controllers
{
    [AuthorizeExhysAdmin]
    public class UserGroupsController : ExhysController
    {
        [HttpGet]
        public ActionResult List()
        {
            AddSignedInUserInformation();
            using (var db = new ExhysContestEntities())
            {
                var groups = new List<UserGroupViewModel>();
                db.UserGroups.ToList().ForEach((g) => { groups.Add(new UserGroupViewModel(g)); });
                return View(groups);
            }
        }

        [HttpPost]
        public ActionResult List(IList<UserGroupViewModel> vm)
        {
            using (var db = new ExhysContestEntities())
            {
                foreach(UserGroupViewModel grvm in vm)
                {
                    UserGroup group = db.UserGroups
                        .Where(g => g.Id == grvm.Id)
                        .Include((g)=>g.AvaiableCompetition)
                        .FirstOrDefault();

                    if (grvm.RequestDelete == false)
                    {
                        group.Name = grvm.Name;
                        group.Description = grvm.Description;
                        group.IsAdministrator = grvm.IsAdmin;
                        group.IsOpen = grvm.IsOpen;
                    }
                    else
                    {
                        db.UserGroups.Remove(group);
                    }
                    db.SaveChanges();
                }
                //db.SaveChanges();
            }
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(UserGroupViewModel vm)
        {
            if(!vm.Validate(ViewData))
            {
                return View(vm);

            }
            using (var db = new ExhysContestEntities())
            {
                var gr = new UserGroup()
                {
                    Name = vm.Name,
                    Description = vm.Description,
                    IsAdministrator = vm.IsAdmin,
                    IsOpen = vm.IsOpen
                };
                db.UserGroups.Add(gr);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

Exhys/Exhys.WebContestHost/Areas/Administration/Views/UserGroups/Add.cshtml
@model UserGroupViewModel
        <div>
            <br /><br />
            <div class="col-lg-6">
                @using (Html.BeginForm("Add", "UserGroups", FormMethod.Post, new { @class = "form-horizontal well" }))
                {
                    <fieldset>
                        <legend>Add Group</legend>
                        @if (Html.ErrorListFor(ViewData) != null)
                        {
                            <div class="alert alert-dismissible alert-danger">
                                <button id="btn-close" type="button" class="close" data-dismiss="alert">×</button>
                                @Html.ErrorListFor(ViewData)
                            </div>
                        }
                        <div class="form-group">
                            @Html.LabelFor(m => m.Name, new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(m => m.Name, new { placeholder = "Group Name", @class = "form-control lineH" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Description, new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextAreaFor(m => m.Description, new { placeholder = "Description", @class = "form-control lineH" })
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(m => m.IsAdmin) Is Administrator
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(m => m.IsOpen, new { @class = "valign-middle" }) Is Open
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-10 col-lg-offset-2">
                                <button type="reset" class="btn btn-default">Reset</button>
                                <button type="submit" class="btn btn-primary">Add Group</button>
                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>

Exhys/Exhys.WebContestHost/Areas/Administration/Views/UserGroups/List.cshtml
@model IList<UserGroupViewModel>
<div>
	@using(Html.BeginForm(FormMethod.Post))
	{
		<br /><br />
		<table border="1" class="table table-hover table-striped table-bordered">
			<thead class="th-center">
				<tr>
					<th>Group Id</th>
					<th>Name</th>
					<th>Description</th>
					<th>Is Admin</th>
					<th>Is Open</th>
					<th>Delete Group</th>
				</tr>
			</thead>
			<tbody>
				@{
					for(int i = 0; i < Model.Count; i++)
					{
						<tr class="valign-middle">
							<td class="text-center">
								@Html.HiddenFor(m => m[i].Id)
								<span>@Model[i].Id</span> 
							</td>
							<td>@Html.TextBoxFor(m => m[i].Name, new { Class = "form-control height-25px" })</td>
							<td>@Html.TextBoxFor(m => m[i].Description, new { Class = "form-control height-25px" })</td>
							<td class="text-center">@Html.CheckBoxFor(m => m[i].IsAdmin)</td>
							<td class="text-center">@Html.CheckBoxFor(m => m[i].IsOpen)</td>
							<td class="text-center">@Html.CheckBoxFor(m => m[i].RequestDelete)</td>
						</tr>
					}
				}
			</tbody>
		</table>
		<button type="submit">Save Changes</button>
					}
</div>