Exhys/Exhys.WebContestHost/Areas/Shared/ViewModels/ParticipationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Exhys.WebContestHost.Areas.Shared.ViewModels
{
    public class ParticipationViewModel
    {
        public CompetitionViewModel Competition { get; set; }
        public List<ProblemSolutionViewModel> ProblemSubmissions { get; set; }
        public UserAccountViewModel User { get; set; }

        public ParticipationViewModel () : this(null) { }
        public int Id { get; set; }
        public ParticipationViewModel (DataModels.Participation model)
        {
            if (model != null)
            {
                this.Competition = new CompetitionViewModel(model.Competition);
                this.Id = model.Id;
                if(model.Submissions!=null)
                {
                    ProblemSubmissions = new List<ProblemSolutionViewModel>();
                    foreach(var v in model.Submissions)
                    {
                        ProblemSubmissions.Add(new ProblemSolutionViewModel(v));
                    }
                }
                if(model.User!=null)
                {
                    this.User = new UserAccountViewModel(model.User);
                }
            }
        }
    }
}

Exhys/Exhys.WebContestHost/Controllers/ParticipationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exhys.WebContestHost.Areas.Shared.Extensions;
using Exhys.WebContestHost.Areas.Shared.Mvc;
using Exhys.WebContestHost.Areas.Shared.ViewModels;
using Exhys.WebContestHost.DataModels;
using System.Data.Entity;
using Exhys.WebContestHost.Areas.Shared;
using System.Threading.Tasks;
using Exhys.WebContestHost.Communication;

namespace Exhys.WebContestHost.Controllers
{
    [AuthorizeExhysUser]
    public class ParticipationController : ExhysController
    {
        [HttpGet]
        public ActionResult Index () => RedirectToAction("List");

        private ActionResult RedirectToList ()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult List ()
        {
            var vm = new List<CompetitionViewModel>();

            using (var db = new ExhysContestEntities())
            {
                var user = Request.GetSignedInUserQuery(db).FirstOrDefault();

                db.Entry(user)
                    .Reference(u => u.UserGroup)
                    .Query()
                    .Include(u => u.AvaiableCompetition).Load();

                var participations = db.Participations
                    .Where(p => p.User.Id == user.Id)
                    .Include(p => p.Competition)
                    .ToList();

                var competitions = user.UserGroup.AvaiableCompetition.ToList();
                foreach (var comp in competitions)
                {
                    var compVm = new CompetitionViewModel(comp);

                    if (participations.Where(p => p.Competition.Id == comp.Id).Count() != 0)
                    {
                        compVm.IsUserParticipating = true;
                    }

                    vm.Add(compVm);
                }
            }

            return View(vm);
        }

        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult Join (int id)
        {
            using (var db = new ExhysContestEntities())
            {
                var competition = db.Competitions.Where(c => c.Id == id).FirstOrDefault();
                if (competition == null)
                {
                    return RedirectToList();
                }
                else
                {
                    return View(new CompetitionViewModel(competition));
                }
            }
        }

        [HttpPost]
        [AuthorizeExhysUser]
        public ActionResult Join (CompetitionViewModel vm)
        {
            using (var db = new ExhysContestEntities())
            {
                var competition = db.Competitions.Where(c => c.Id == vm.Id).FirstOrDefault();
                if (competition == null) return RedirectToAction("List");

                var user = Request.GetSignedInUserQuery(db).FirstOrDefault();

                var participation = db.Participations
                    .Where(p => p.User.Id == user.Id && p.Competition.Id == competition.Id)
                    .FirstOrDefault();
                if (participation != null) return RedirectToAction("Participate", new { id = vm.Id });

                participation = new DataModels.Participation();
                db.Entry(participation).State = EntityState.Added;

                participation.Competition = competition;
                participation.User = user;

                db.SaveChanges();

                return RedirectToAction("Participate", new { id = competition.Id });

            }
        }

        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult Participate (int? id)
        {
            if (id == null)
            {
                id = Request.GetCurrentCompetitionCookie();
                if (id == null)
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                Response.SetCurrentCompetitionCookie(id.Value);
            }

            using (var db = new ExhysContestEntities())
            {
                AddProgrammingLanguageOptions(db);
                AddProblemOptions(db, id.Value);

                var competition = db.Competitions.Where(c => c.Id == id)

                    .FirstOrDefault();
                if (competition == null) return RedirectToList();

                var user = Request.GetSignedInUserQuery(db).FirstOrDefault();

                var participation = db.Participations
                    .Where(p => p.User.Id == user.Id && p.Competition.Id == competition.Id)
                    .Include(p => p.Competition.Problems.Select(prob => prob.ProblemStatements))
                    .Include(p => p.Submissions)
                    .FirstOrDefault();
                if (participation == null) return RedirectToList();

                var vm = new ParticipationViewModel(participation);
                vm.Competition.IncludeProblems().IncludeProblemStatements();

                return View(vm);
            }
        }
         
        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult DownloadStatement (int id)
        {
            using (var db = new ExhysContestEntities())
            {
                ProblemStatement statement = db.ProblemStatements
                    .Where(s => s.Id == id)
                    .FirstOrDefault();

                return File(fileContents: statement.Bytes, fileDownloadName: statement.Filename, contentType: "application/zip");
            }
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult SubmitSolution (ProblemSolutionViewModel vm)
        {
            string baseUrl = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~/");
            string serviceUrl = baseUrl + "/ExhysService.svc";

            using (var db = new ExhysContestEntities())
            {
                var problem = db.Problems
                    .Where(p => p.Id == vm.ProblemId)
                    .Include(p => p.ProblemSolutions)
                    .Include(p => p.CompetitionGivenAt)
                    .FirstOrDefault();
                var competition = db.Competitions
                    .Where(c => c.Id == problem.CompetitionGivenAt.Id)
                    .Include(c => c.Participations)
                    .FirstOrDefault();
                var user = Request
                    .GetSignedInUserQuery(db)
                    .Include(u => u.Participations)
                    .FirstOrDefault();
                var participation = db.Participations
                    .Where(p => p.User.Id == user.Id && p.Competition.Id == competition.Id)
                    .FirstOrDefault();

                var solution = new ProblemSolution()
                {
                    LanguageAlias = vm.LanguageAlias,
                    Participation = participation,
                    Problem = problem,
                    Status = ProblemSolution.ExecutionStatus.Pending,
                    SourceCode = vm.SourceCode,
                    Message = ""
                };

                db.ProblemSolutions.Add(solution);
                db.SaveChanges();

                int solutionId = db.Entry(solution).Entity.Id;

                Task.Run(() =>
                {
                    HandleSolution(solutionId,serviceUrl);
                })
                .ContinueWith((x) =>
                {
                    throw new Exception();
                }, TaskContinuationOptions.OnlyOnFaulted);

                return RedirectToAction("Participate");
            }
        }

        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult ViewSubmission(int id)
        {
            using (var db = new ExhysContestEntities())
            {
                var user = Request.GetSignedInUserQuery(db).FirstOrDefault();
                var submission = db.ProblemSolutions
                    .Where(x => x.Id == id)
                    .Where(x=>x.Participation.User.Id==user.Id)
                    .Include(x=>x.Problem)
                    .Include(x=>x.TestStatuses.Select(y=>y.ProblemTest))
                    .FirstOrDefault();
                if (submission == null) throw new Exception("This submission does not exist or you don't have permissions to view it.");


                return View(new ProblemSolutionViewModel(submission));
            }
        }

        [HttpGet]
        [AuthorizeExhysUser]
        public ActionResult ListSubmissions (int participationId)
        {
            List<ProblemSolutionViewModel> vm;
            using (var db = new ExhysContestEntities())
            {
                var user = Request.GetSignedInUserQuery(db).FirstOrDefault();
                if (user == null) { return Content("Not Signed In"); }

                var participation = db.Participations
                    .Where(p => p.Id == participationId)
                    .FirstOrDefault();

                var sols = db.ProblemSolutions
                    .Where(x => x.Participation.Id == participationId)
                    .Where(x => x.Participation.User.Id == user.Id)
                    .Include(x=>x.Problem)
                    .Include(x => x.TestStatuses)
                    .Include(x => x.TestStatuses.Select(y => y.ProblemTest))
                    .ToList();

                ;

                vm = sols
                    .Select(x => new ProblemSolutionViewModel(x))
                    .ToList();
            }
            return PartialView(vm);
        }

        private void HandleSolution (int solutionId, string serviceUrl)
        {

Exhys/Exhys.WebContestHost/Views/Participation/Join.cshtml
@model CompetitionViewModel
<region>
    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Id);
        @Html.HiddenFor(m=>m.Name)
        @Html.HiddenFor(m=>m.Description)
        @Html.HiddenFor(m=>m.GroupId)
        <div>
			<h3>Are you sure you want to join this competition?</h3>
        </div>
        <div>
			<h4>@Model.Name</h4>
        </div>
        <div>
            @Model.Description
        </div>
		<br/>
        <div>
            <button class="btn btn-primary" type="submit">Yes</button>
            <button class="btn" type="button" onclick="window.history.back();">No</button>
        </div>
    }
</region>

Exhys/Exhys.WebContestHost/Views/Participation/List.cshtml
@model IList<CompetitionViewModel>
@{
	ViewData.SetPageTitle("List Competitions");
}
<div>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Join</th>
			</tr>
		</thead>

		<tbody>
			@foreach(var competition in Model)
			{
				<tr>
					<td>@competition.Name</td>
					<td>@competition.Description</td>
					<td>
						@if(competition.IsUserParticipating == false)
						{
							using(Html.BeginForm("Join", "Participation", FormMethod.Get))
							{
								<input type="hidden" name="id" value="@competition.Id" />
								<button class="btn height-27px padding-1" type="submit">Join</button>
							}
						}
						else
						{
							using(Html.BeginForm("Participate", "Participation", FormMethod.Get))
							{
								<input type="hidden" name="id" value="@competition.Id" />
								<button class="btn btn-primary height-27px padding-1" type="submit">Already Joined</button>
							}
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

Exhys/Exhys.WebContestHost/Views/Participation/ListSubmissions.cshtml
@model List<ProblemSolutionViewModel>
	<fieldset>
		<legend>Previous Submissions</legend>
		<table class="table-bordered table">
			<thead class="th-center">
				<tr>
					<th>Problem</th>
					<th>Status</th>
					<th>Total Score</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				@{
					foreach(var v in Model)
					{
						double totalScore = 0, totalPossible = 0;
						<tr>
							<td class="text-center">@v.ProblemName</td>
							<td class="text-center">
								@{  
                                    if (v.Status == ProblemSolutionExecutionStatusVm.Pending)
                                    {
                                        <span>Pending</span>
                                    }
                                    else if(v.Status == ProblemSolutionExecutionStatusVm.InProgress)
                                    {
                                         <span>In Progress...</span>
                                    }
                                    else if (v.Status == ProblemSolutionExecutionStatusVm.ExecutionFailed)
                                    {
                                        <span>Execution Failed...</span>
                                    }
                                    else if (v.Status == ProblemSolutionExecutionStatusVm.Completed)
                                    {
                                        <span>Completed</span>
                                    /*}
                                    else
                                    {*/
                                        foreach (var status in v.TestStatuses)
                                        {
											<span>
												@{
													string s;
													if(!status.Score.Equals(double.NaN))
													{
														s = status.Score.ToString();
														totalScore += status.Score;
														totalPossible += status.PossibleScore;
													}
													else
													{
														s = "?";
													}
													@s

												}
											</span>
										}
									}
								}
							</td>
							<td class="text-center">
								@totalScore / @totalPossible
							</td>
							<td class="text-center">
								@using(Html.BeginForm(actionName: "ViewSubmission", method: FormMethod.Get, controllerName: "Participation", routeValues: new { id = v.Id }))
								{
									<button class="btn btn-primary height-27px padding-1 width-100" type="submit">Click</button>
								}
							</td>
						</tr>
													}
				}
			</tbody>
		</table>
	</fieldset>

Exhys/Exhys.WebContestHost/Views/Participation/Participate.cshtml
@model ParticipationViewModel
@section scripts{
	<script type="text/javascript">

		function refreshSubmissions() {
			$.ajaxSetup({
				cache: false
			});
			var currentHeight = $("#submissions-list").height();
			$('#submissions-list').css("height", currentHeight);
			$.ajax(
				{
					url: '@Url.Action("ListSubmissions", "Participation")?participationId=@Model.Id',
					success: function (result) {
						$("#submissions-list").html(result)
							.promise()
							.done(function () {
								$("#submissions-list").css("height", "");
								currentHeight = $("#submissions-list").height();
								$('#submissions-list').css("height", currentHeight);
							});
					}
				});
		}
	    $(document).ready(function () {
		    setInterval(refreshSubmissions, 5000);
	    });
		function resizeTextarea(id) {
			var a = document.getElementById(id);
			a.style.height = 'auto';
			a.style.height = a.scrollHeight+25 + 'px';
		}

		function init() {
			var a = document.getElementsByTagName('inputLarge');
			for (var i = 0, inb = a.length; i < inb; i++) {
				if (a[i].getAttribute('data-resizable') == 'true')
					resizeTextarea(a[i].id);
			}
		}

		addEventListener('DOMContentLoaded', init);
	</script>
}
@if(Model != null && Model.Competition != null)
{
	<h2 class="text-center">@Model.Competition.Name</h2>
}


@*Problem List*@
<div class="form-group">
	<section style="float:left" class="col-lg-4">
		<fieldset>
			<legend>Problems</legend>
			<table class="table-bordered table">

				<tbody>
					@for(int i = 0; i < Model.Competition.Problems.Count; i++)
					{
						<tr>
							<th width="50%">@Model.Competition.Problems[i].Name</th>
							<td width="50%">
								@for(int j = 0; j < Model.Competition.Problems[i].ProblemStatements.Count; j++)
								{
									<div class="padding-0 center">
										@using(Html.BeginForm(method: FormMethod.Get, actionName: "DownloadStatement", controllerName: "Participation"))
										{
											<input type="hidden" name="id" value="@Model.Competition.Problems[i].ProblemStatements[j].Id" />
											<button type="submit" class="btn btn-link height-25px padding-0">@Model.Competition.Problems[i].ProblemStatements[j].Filename.Split('\\').Last()</button>
										}
									</div>
								}
							</td>
						</tr>
					}
				</tbody>
			</table>
		</fieldset>
		<br/><br />
		<div id="submissions-list" style="display: inline-block">
			@{Html.RenderAction(actionName: "ListSubmissions", controllerName: "Participation", routeValues: new { participationId = Model.Id });}
		</div>
		<br /><br /><br /><br />
	</section>


	@*Submission*@
	<section style="padding-left:1cm;">
		@using(Html.BeginForm(actionName: "SubmitSolution", controllerName: "Participation", method: FormMethod.Post, htmlAttributes: new { }))
		{
			var vm = new ProblemSolutionViewModel();

			<fieldset>
				<legend>Submit a Solution</legend>
				<div class="form-group">
					@Html.LabelFor(m => vm.ProblemId, "Problem")
					@Html.FixedDropDownListFor(m => vm.ProblemId, ViewData.GetProblemOptions(), new { @class = "form-control" })
				</div>

				<div class="form-group">
					@Html.LabelFor(m => vm.SourceCode, "Source Code")
					@Html.TextAreaFor(m => vm.SourceCode, new { placeholder = "//Hello, World!", @class = "form-control input-lg font-size-14", id = "inputLarge" ,onkeyup = "resizeTextarea('inputLarge')", wrap = "off" })
				</div>

				<div class="form-group">
					@Html.LabelFor(m => vm.LanguageAlias, "Language")
					@Html.FixedDropDownListFor(m => vm.LanguageAlias, ViewData.GetProgrammingLanguageOptions(), new { @class = "form-control" })
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Submit Solution</button>
					<button class="btn btn-default" type="reset">Reset</button>
				</div>
			</fieldset>
		}

	</section>
</div>

<br /><br /><br />

Exhys/Exhys.WebContestHost/Views/Participation/ViewSubmission.cshtml
@model ProblemSolutionViewModel
    <fieldset>
		@{
			var status = Model.Status;
			string statusStr = "";
			if(status == ProblemSolutionExecutionStatusVm.Completed) { statusStr = "Completed"; }
			else if(status == ProblemSolutionExecutionStatusVm.InProgress) { statusStr = "In Progress..."; }
			else if(status == ProblemSolutionExecutionStatusVm.Pending) { statusStr = "Pending"; }
		}
        <legend>Status:  @statusStr</legend>
		<table class="table-hover table-bordered table">
			<thead class="th-center">
				<tr>
					<th>Test</th>
					<th>Score</th>
					<th>Status</th>
					<th>Input</th>
					<th>Output</th>
					<th>Solution</th>
				</tr>
			</thead>
			<tbody>
				@{
					double totalScore = 0, totalPossible = 0;
					var statuses = Model.TestStatuses;
					for(int i = 0; i < statuses.Count; i++)
					{
						<tr>
							<td>@(i + 1)</td>
							<td>
								@{
									string s = "";
									if(!statuses[i].Score.Equals(double.NaN))
									{
										s = statuses[i].Score.ToString();
										totalScore += statuses[i].Score;
										totalPossible += statuses[i].PossibleScore;
									}
									else
									{
										s = "?";
									}
									@s
								}
							</td>
							<td>
								@{
									var sts = statuses[i].Status;
									string stsStr = "";
									if(sts == TestStatusVm.CorrectAnswer) { stsStr = "Correct Answer"; }
									if(sts == TestStatusVm.MemoryLimitExceeded) { stsStr = "Memory exceeded"; }
									if(sts == TestStatusVm.SegmentationFault) { stsStr = "Segmentation Fault"; }
									if(sts == TestStatusVm.TimeOut) { stsStr = "Timeout"; }
									if(sts == TestStatusVm.WrongAnswer) { stsStr = "Wrong Answer"; }
									if(sts == TestStatusVm.NoFeedback) { stsStr = "No Feedback"; }
									@stsStr
								}
							</td>
							<td>
								@if(!string.IsNullOrEmpty(statuses[i].Input))
								{<code>@statuses[i].Input</code>}
								else
								{@("No Feedback")}
							</td>
							<td>
								@if(!string.IsNullOrEmpty(statuses[i].Output))
								{<code>@statuses[i].Output</code>}
								else
								{@("No Feedback")}
							</td>
							<td>
								@if(!string.IsNullOrEmpty(statuses[i].Solution))
								{<code>@statuses[i].Solution</code>}
								else
								{@("No Feedback")}
							</td>
						</tr>
									}
				}
				<tr>
					<th class="text-center">Total</th>
					<td colspan="5">@totalScore / @totalPossible</td>
				</tr>
			</tbody>
		</table>

    </fieldset>

    <br />
    <fieldset>
        <legend>Source Code</legend>
        <code style="white-space:pre-wrap; width:100%; padding-left:0px;">@Model.SourceCode.Trim()</code>
    </fieldset>
	<br /><br /><br /><br /><br />